"""empty message

Revision ID: 32f01dc4c41f
Revises: 
Create Date: 2019-03-13 15:06:28.876782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f01dc4c41f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=20), nullable=True),
    sa.Column('itemAmount', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemAmount'),
    sa.UniqueConstraint('itemName')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('classCode', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('numOfGuests', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_state')
    op.drop_table('student')
    op.drop_table('bag')
    # ### end Alembic commands ###
