"""empty message

Revision ID: f42f16049339
Revises: 
Create Date: 2019-03-13 22:12:22.006452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42f16049339'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('classCode', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('numOfGuests', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId')
    )
    op.create_table('bag_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=20), nullable=True),
    sa.Column('itemAmount', sa.Integer(), nullable=True),
    sa.Column('gameStateId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameStateId'], ['game_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemName')
    )
    op.create_table('canvas_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=20), nullable=True),
    sa.Column('itemAmount', sa.Integer(), nullable=True),
    sa.Column('gameStateId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameStateId'], ['game_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemName')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=20), nullable=True),
    sa.Column('answer', sa.Numeric(), nullable=True),
    sa.Column('arithmeticType', sa.String(length=20), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('gameStateId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameStateId'], ['game_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('canvas_item')
    op.drop_table('bag_item')
    op.drop_table('game_state')
    op.drop_table('student')
    # ### end Alembic commands ###
